name: test02
run-name: test02

on:
  workflow_dispatch:
  push:


jobs:
  test:
    uses: PavansaiPashikanti/test03/.github/workflows/test03.yml@main
    with:
      test: |
        echo "$secrets.test"
    secrets: inherit