name: test03
run-name: test03

on:
  workflow_call:
    inputs:
      test: 
        description: "agsjfdgbak"
        type: string


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          ${{ inputs.test }}